### ISSUE TITLE
文字エンコードがバラバラ

### ISSUE THREAD

**Issue by SatoshiShimada** [YusukeKato/RPG#5]
どれかに統一する

**Comment by YusukeKato** [comment]
了解。任せます。

**Comment by SatoshiShimada** [comment]
火曜日に行います
UTF-8エンコーディングに統一しましょう

**Comment by SatoshiShimada** [comment]
UTF-8に統一しましたが、EasyIDECという開発環境で保存すると文字コードが変わるようです。
それほど重要な問題でもないのであきらめます。
